"""Generate docs/API.md: Markdown reference of every backend route.

Usage:
    python -m app.scripts.api_docs          # write docs/API.md
    python -m app.scripts.api_docs --check  # exit 1 if docs/API.md is stale
"""

from __future__ import annotations

import sys
from pathlib import Path

from app.route_inventory import iter_routes


DOCS_PATH = Path(__file__).resolve().parents[3] / "docs" / "API.md"

ROLE_ORDER = ["public", "user", "admin", "undeclared"]
ROLE_HEADINGS = {
    "public": "## Public routes",
    "user": "## User routes (requires authentication)",
    "admin": "## Admin routes",
    "undeclared": "## Undeclared routes (no role declared)",
}


def _escape_pipe(text: str) -> str:
    """Escape pipe characters in table cells."""
    return text.replace("|", "\\|")


def _role_group(roles: set[str]) -> str:
    """Determine which group a route belongs to based on its roles.

    Priority: admin > user > public > undeclared.
    A route requiring admin goes in admin group even if it also requires user auth.
    """
    if "admin" in roles:
        return "admin"
    if "user" in roles:
        return "user"
    if "public" in roles:
        return "public"
    return "undeclared"


def _format_route_row(method: str, path: str, summary: str) -> str:
    """Format a single route as a Markdown table row."""
    summary_escaped = _escape_pipe(summary)
    return f"| {method} | {path} | {summary_escaped} |"


def generate_api_docs() -> str:
    """Generate the full API.md content as a string."""
    routes_by_role: dict[str, list[tuple[str, str, str]]] = {r: [] for r in ROLE_ORDER}

    for method, path, roles, summary in iter_routes():
        group = _role_group(roles)
        routes_by_role[group].append((method, path, summary))

    # Sort each group by path, then method
    for group in routes_by_role:
        routes_by_role[group].sort(key=lambda x: (x[1], x[0]))

    # Count totals per group
    totals = {group: len(routes) for group, routes in routes_by_role.items()}
    total_routes = sum(totals.values())

    lines = []
    lines.append("# GlassBox API reference")
    lines.append("")
    lines.append(
        "> This file is generated by `python -m app.scripts.api_docs` and must not be edited by hand."
    )
    lines.append("")
    lines.append(
        f"Total routes: {total_routes} "
        f"(public: {totals['public']}, user: {totals['user']}, admin: {totals['admin']}, undeclared: {totals['undeclared']})"
    )
    lines.append("")
    lines.append("> The public interactive docs will live at `/api/docs`.")
    lines.append("")

    for i, role in enumerate(ROLE_ORDER):
        routes = routes_by_role[role]
        lines.append(ROLE_HEADINGS[role])
        lines.append("")
        if routes:
            lines.append("| Method | Path | Summary |")
            lines.append("|--------|------|---------|")
            for method, path, summary in routes:
                lines.append(_format_route_row(method, path, summary))
        else:
            lines.append("*No routes in this group.*")
        if i != len(ROLE_ORDER) - 1:
            lines.append("")

    return "\n".join(lines)


def write_docs() -> None:
    """Write the generated API docs to docs/API.md."""
    content = generate_api_docs()
    DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOCS_PATH.write_text(content + "\n", encoding="utf-8")
    print(f"Generated {DOCS_PATH} ({len(content.splitlines())} lines)")


def check_docs() -> int:
    """Check if docs/API.md is up to date. Returns 0 if current, 1 if stale."""
    current = generate_api_docs()
    if not DOCS_PATH.exists():
        print("docs/API.md is out of date: run python -m app.scripts.api_docs", file=sys.stderr)
        return 1
    existing = DOCS_PATH.read_text(encoding="utf-8").rstrip("\n")
    if current != existing:
        print("docs/API.md is out of date: run python -m app.scripts.api_docs", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    if "--check" in sys.argv:
        sys.exit(check_docs())
    else:
        write_docs()